name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openshift_testpage:$(date +%s)
